import jax
import jax.numpy as jnp
from jax import random


def sampler_mixture_bump(
        key,
        m,
        n,
        d,
        n_inj=0,
        mu=20,
        mu_inj=22,
        std_mu=1,
        std_inj=0.1,
    return_label=False,
):
    """
    Sampler Mixture of Gaussians.

    Returns samples X of shape (m, d) and Y of shape (n, d).
    
    Mixture of four Gaussians with means 
        (mu, mu), (-mu, mu), (mu, -mu), (-mu, -mu)
    for the first two dimensions and zeros for the other dimensions,
    and standard deviations
        std_1, std_1, std_1, std_X_Y 
    where std_X_Y is std_1 for X and std_2 for Y.

    Parameters
    ----------
    key:
        Jax random key (can be generated by jax.random.PRNGKey(seed) for an integer seed).
    m : int
        Number of samples for X.
    n : int
        Number of samples for Y.
    d: int
        Dimension for both X and Y (greater of equal to 2).
    mu: scalar
        mean parameter of the Gaussians as explained above.
    std_1: scalar
        standard deviation parameter for the Gaussians as explained above.
    std_2: scalar
        standard deviation parameter for the Gaussians as explained above.

    Returns
    -------
    X : array_like
        Array of shape (m, d).
    Y : array_like
        Array of shape (n, d).
    """
    assert d >= 2
    
    def sampler_normal(key, mu_1, mu_2, std, N, d):
        mean = jnp.zeros((d, ))
        mean = mean.at[0].set(mu_1)
        mean = mean.at[1].set(mu_2)
        cov = jnp.eye(d) * std ** 2
        return jax.random.multivariate_normal(key, mean, cov, shape=(N,)) 
    
    # X
    key, subkey = random.split(key)
    subkeys = random.split(subkey, num=6)
    choice = jax.random.choice(subkeys[0], jnp.arange(4), shape=(m,))
    m_0 = jnp.sum(choice == 0)  # m = m_0 + m_1 + m_2 + m_3
    m_1 = jnp.sum(choice == 1)
    m_2 = jnp.sum(choice == 2)
    m_3 = jnp.sum(choice == 3)
    mu_pairs = ((mu, mu), (-mu, mu), (mu, -mu), (-mu, -mu))
    std = std_mu
    samples_0 = sampler_normal(subkeys[1], *mu_pairs[0], std, m_0, d)
    samples_1 = sampler_normal(subkeys[2], *mu_pairs[1], std, m_1, d)
    samples_2 = sampler_normal(subkeys[3], *mu_pairs[2], std, m_2, d)
    samples_3 = sampler_normal(subkeys[4], *mu_pairs[3], std, m_3, d)
    X = jnp.concatenate((samples_0, samples_1, samples_2, samples_3))
    X = jax.random.permutation(subkeys[5], X, axis=0)
    X_label = jnp.concatenate((0*jnp.ones(m_0), 1*jnp.ones(m_1), 2*jnp.ones(m_2), 3*jnp.ones(m_3)))
    X_label = jax.random.permutation(subkeys[5], X_label, axis=0)
    # Y
    key, subkey = random.split(key)
    subkeys = random.split(subkey, num=7)
    choice = jax.random.choice(subkeys[0], jnp.arange(4), shape=(n,))
    n_0 = jnp.sum(choice == 0)  # n = n_0 + n_1 + n_2 + n_3
    n_1 = jnp.sum(choice == 1)
    n_2 = jnp.sum(choice == 2)
    n_3 = jnp.sum(choice == 3)
    mu_pairs = ((mu, mu), (-mu, mu), (mu, -mu), (-mu, -mu), (-mu_inj, -mu_inj))
    std = std_mu
    samples_0 = sampler_normal(subkeys[1], *mu_pairs[0], std, n_0, d)
    samples_1 = sampler_normal(subkeys[2], *mu_pairs[1], std, n_1, d)
    samples_2 = sampler_normal(subkeys[3], *mu_pairs[2], std, n_2, d)
    samples_3 = sampler_normal(subkeys[4], *mu_pairs[3], std, n_3, d)
    bump = sampler_normal(subkeys[5], *mu_pairs[4], std_inj, n_inj, d)
    
    Y = jnp.concatenate((samples_0, samples_1, samples_2, samples_3, bump))
    Y = jax.random.permutation(subkeys[6], Y, axis=0)
    if return_label: return X, Y, X_label
    else: return X, Y
